wiki/web/forms.py
"""
    Forms
    ~~~~~
"""
from flask_wtf import Form
from wtforms import BooleanField
from wtforms import TextField
from wtforms import TextAreaField
from wtforms import PasswordField
from wtforms.validators import InputRequired
from wtforms.validators import ValidationError

from wiki.core import clean_url
from wiki.web import current_wiki
from wiki.web import current_users


class URLForm(Form):
    url = TextField('', [InputRequired()])

    def validate_url(form, field):
        if current_wiki.exists(field.data):
            raise ValidationError('The URL "%s" exists already.' % field.data)

    def clean_url(self, url):
        return clean_url(url)


class SearchForm(Form):
    term = TextField('', [InputRequired()])
    ignore_case = BooleanField(
        description='Ignore Case',
        # FIXME: default is not correctly populated
        default=True)


class EditorForm(Form):
    title = TextField('', [InputRequired()])
    body = TextAreaField('', [InputRequired()])
    tags = TextField('')


class LoginForm(Form):
    name = TextField('', [InputRequired()])
    password = PasswordField('', [InputRequired()])

    def validate_name(form, field):
        user = current_users.get_user(field.data)
        if not user:
            raise ValidationError('This username does not exist.')

    def validate_password(form, field):
        user = current_users.get_user(form.name.data)
        if not user:
            return
        if not user.check_password(field.data):
            raise ValidationError('Username and password do not match.')

wiki/web/__init__.py
import os

from flask import current_app
from flask import Flask
from flask import g
from flask_login import LoginManager
from werkzeug.local import LocalProxy

from wiki.core import Wiki
from wiki.web.user import UserManager

class WikiError(Exception):
    pass

def get_wiki():
    wiki = getattr(g, '_wiki', None)
    if wiki is None:
        wiki = g._wiki = Wiki(current_app.config['CONTENT_DIR'])
    return wiki

current_wiki = LocalProxy(get_wiki)

def get_users():
    users = getattr(g, '_users', None)
    if users is None:
        users = g._users = UserManager(current_app.config['CONTENT_DIR'])
    return users

current_users = LocalProxy(get_users)


def create_app(directory):
    app = Flask(__name__)
    app.config['CONTENT_DIR'] = directory
    app.config['TITLE'] = u'wiki'
    try:
        app.config.from_pyfile(
            os.path.join(app.config.get('CONTENT_DIR'), 'config.py')
        )
    except IOError:
        msg = "You need to place a config.py in your content directory."
        raise WikiError(msg)

    loginmanager.init_app(app)

    from wiki.web.routes import bp
    app.register_blueprint(bp)

    return app


loginmanager = LoginManager()
loginmanager.login_view = 'wiki.user_login'

@loginmanager.user_loader
def load_user(name):
    return current_users.get_user(name)

wiki/web/routes.py
"""
    Routes
    ~~~~~~
"""
from flask import Blueprint
from flask import flash
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for
from flask import abort
from flask import send_from_directory
from flask_login import current_user
from flask_login import login_required
from flask_login import login_user
from flask_login import logout_user

from wiki.core import Processor
from wiki.web.forms import EditorForm
from wiki.web.forms import LoginForm
from wiki.web.forms import SearchForm
from wiki.web.forms import URLForm
from wiki.web import current_wiki
from wiki.web import current_users
from wiki.web.user import protect

import os.path as op
import logging

bp = Blueprint('wiki', __name__)


@bp.route('/')
@protect
def home():
    page = current_wiki.get('home')
    if page:
        return display('home')
    return render_template('home.html')

@bp.route('/index/<path:url>/')
@bp.route('/index/')
@protect
def index(url=""):
    #<path:url>/
    pages = current_wiki.index(url)
    directories = current_wiki.index_dir(url)
    return render_template('index.html', pages=pages,directories=directories)

@bp.route('/content/<path:url>/')
@protect
def content(url):
    path = op.join(current_wiki.root,url)
    if op.isfile(path):
        return send_from_directory(op.dirname(path),op.basename(path))
    abort(404)

@bp.route('/<path:url>/')
@protect
def display(url):
    if "media" in url:
        logging.info("media"+url)
        return content(url)
    page = current_wiki.get_or_404(url)
    return render_template('page.html', page=page)

@bp.route('/create/', methods=['GET', 'POST'])
@protect
def create():
    form = URLForm()
    if form.validate_on_submit():
        return redirect(url_for(
            'wiki.edit', url=form.clean_url(form.url.data)))
    return render_template('create.html', form=form)


@bp.route('/edit/<path:url>/', methods=['GET', 'POST'])
@protect
def edit(url):
    page = current_wiki.get(url)
    form = EditorForm(obj=page)
    if form.validate_on_submit():
        if not page:
            page = current_wiki.get_bare(url)
        form.populate_obj(page)
        page.save()
        flash('"%s" was saved.' % page.title, 'success')
        return redirect(url_for('wiki.display', url=url))
    return render_template('editor.html', form=form, page=page)


@bp.route('/preview/', methods=['POST'])
@protect
def preview():
    data = {}
    processor = Processor(request.form['body'])
    data['html'], data['body'], data['meta'] = processor.process()
    return data['html']


@bp.route('/move/<path:url>/', methods=['GET', 'POST'])
@protect
def move(url):
    page = current_wiki.get_or_404(url)
    form = URLForm(obj=page)
    if form.validate_on_submit():
        newurl = form.url.data
        current_wiki.move(url, newurl)
        return redirect(url_for('wiki.display', url=newurl))
    return render_template('move.html', form=form, page=page)


@bp.route('/delete/<path:url>/')
@protect
def delete(url):
    page = current_wiki.get_or_404(url)
    current_wiki.delete(url)
    flash('Page "%s" was deleted.' % page.title, 'success')
    return redirect(url_for('wiki.home'))


@bp.route('/tags/')
@protect
def tags():
    tags = current_wiki.get_tags()
    return render_template('tags.html', tags=tags)


@bp.route('/tag/<string:name>/')
@protect
def tag(name):
    tagged = current_wiki.index_by_tag(name)
    return render_template('tag.html', pages=tagged, tag=name)


@bp.route('/search/', methods=['GET', 'POST'])
@protect
def search():
    #
    if 'term' in request.form:
        results = current_wiki.search(request.form["term"], True)
        return render_template('search.html', results=results, search=request.form["term"])
#    term = request.form
    # form = SearchForm()
    # if form.validate_on_submit():
    #     results = current_wiki.search(form.term.data, form.ignore_case.data)
    #     return render_template('search.html', form=form,
    #                           results=results, search=form.term.data)
    return render_template('search.html', search=None)


@bp.route('/user/login/', methods=['GET', 'POST'])
def user_login():
    form = LoginForm()
    if form.validate_on_submit():
        user = current_users.get_user(form.name.data)
        login_user(user)
        user.set('authenticated', True)
        flash('Login successful.', 'success')
        return redirect(request.args.get("next") or url_for('wiki.index'))
    return render_template('login.html', form=form)


@bp.route('/user/logout/')
@login_required
def user_logout():
    current_user.set('authenticated', False)
    logout_user()
    flash('Logout successful.', 'success')
    return redirect(url_for('wiki.index'))


@bp.route('/user/')
def user_index():
    pass


@bp.route('/user/create/')
def user_create():
    pass


@bp.route('/user/<int:user_id>/')
def user_admin(user_id):
    pass


@bp.route('/user/delete/<int:user_id>/')
def user_delete(user_id):
    pass


"""
    Error Handlers
    ~~~~~~~~~~~~~~
"""


@bp.errorhandler(404)
def page_not_found(error):
    return render_template('404.html'), 404

wiki/web/templates/base.html
{% from "helpers.html" import input %}
<!DOCTYPE html>
<html>
	{% include 'head.html' %}
<body class="bg">
  {% include 'menu.html' %}
		<div class="container content-wrap">
			<div class="row">
				<div class="col-sm-8 col-md-8 ">
					{% block header %}
						<div class="page-header">
							<h1>{% block title %}{{ page.title }}{% endblock title %}</h1>
						</div>
					{% endblock header %}
				</div>
				<div class="col-md-4  mb-4">
					<div class="my-sidebar" >
					{% block sidebar %}
					{% endblock sidebar %}
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-8">
					{% with messages = get_flashed_messages(with_categories=True) %}
						{% if messages %}
							{% for category, message in messages %}
									<div class="alert alert-{{ category }} alert-warning alert-dismissable">
									<button type="button" class="close" data-dismiss="alert">×</button>
									{{ message }}
								</div>
							{% endfor %}
						{% endif %}
					{% endwith %}
					{% if form and form.errors %}
						<div class="alert alert-error alert-warning">Errors occured verifying your input. Please check the marked fields below.</div>
					{% endif %}
					{% block content %}
					{% endblock content %}
				</div>
			</div>
		</div>
		{% include 'footer.html' %}
		<script type="text/javascript">
			var images = document.getElementsByTagName('img');
		  for (var i = images.length - 1; i >= 0; i--) {
		    var img = images[i];
				img.className += 'img-fluid'
		  }
			var tocs = document.getElementsByClassName('toc');
			for (var i = 0; i < tocs.length; i++) {
				 document.getElementById('toc-sidebar').appendChild(tocs[i]);
			}
			var tables = document.getElementsByTagName('table');
		  for (var i = tables.length - 1; i >= 0; i--) {
		    var table = tables[i];
				table.className += 'table table-striped'
		  }
			var ps = document.getElementsByTagName('p');
		  for (var i = ps.length - 1; i >= 0; i--) {
		    var p = ps[i];
				p.className += 'text-justify'
		  }

		  {% block postscripts %}
		  {% endblock postscripts %}
		</script>
	</body>
</html>

wiki/web/templates/create.html
{% extends "base.html" %}

{% block title %}Create a new page{% endblock title %}
{% block content %}
<form method="POST" class="form-inline">
	{{ form.hidden_tag() }}
	<div class="form-group mx-sm-3 mb-2"">
	{{ input(form.url, placeholder="URL of the new page", autocomplete="off",class="form-control") }}
	</div>
	<button type="submit" class="btn btn-success mb-2">Create</button>
</form>
{% endblock content %}

{% block sidebar %}
<p class="alert alert-success">Thank you for creating new content!</p>
{% endblock sidebar %}

wiki/web/templates/editor.html
{% from "helpers.html" import input %}
<!DOCTYPE html>
<html>
	{% include 'head.html' %}
<body class="bg">
  {% include 'menu.html' %}
		<div class="container content-wrap">
			<div class="row">
				<div class="col-sm-8 col-md-8 ">
					{% block header %}
						<div class="page-header">
							<h1>{% block title %}{{ page.title }}{% endblock title %}</h1>
						</div>
					{% endblock header %}
				</div>
			</div>
			<div class="row">
				<div class="col-md-10 ">
					{% with messages = get_flashed_messages(with_categories=True) %}
						{% if messages %}
							{% for category, message in messages %}
									<div class="alert alert-{{ category }} alert-warning alert-dismissable">
									<button type="button" class="close" data-dismiss="alert">×</button>
									{{ message }}
								</div>
							{% endfor %}
						{% endif %}
					{% endwith %}
					{% if form and form.errors %}
						<div class="alert alert-error alert-warning">Errors occured verifying your input. Please check the marked fields below.</div>
					{% endif %}
					</div>
				</div>

				<form method="post" class="form">
				{{ form.hidden_tag() }}
				<div class="row">
					<div class="col-md-6">
						{{ input(form.title, placeholder="Title", class="col-md-11", autocomplete="off") }}
						{{ input(form.tags, placeholder="Tags (comma separated)", class="col-md-11", autocomplete="off") }}
					</div>
					<div class="pull-right">
					  <button class="btn btn-danger" onclick="window.location.href='{{ url_for('wiki.display', url=page.url) }}'">Cancel</button>
					  <button  class="btn btn-success" type="submit">Save</button>
					</div>
				</div>
				<div class="row">
						<div class="col-md-6">
							{{ input(form.body, placeholder="Markdown", class="span7 col-md-11", rows="200",id="text-input", oninput="this.editor.update()") }}
						</div>
						<div class="col-md-6">
							<div id="preview"> </div>
						</div>
				</div>

			</form>
		</div>
		{% include 'footer.html' %}
		<script type="text/javascript">
			function Editor(input, preview) {
				this.update = function () {
					preview.innerHTML = markdown.toHTML(input.value);

					for (var i = images.length - 1; i >= 0; i--) {
						var img = images[i];
						img.className += "img-fluid"
					}

					var clientHeight = document.getElementById('preview').clientHeight;
					var tt = document.getElementById("preview").getBoundingClientRect().bottom;
					console.log(clientHeight,tt)
					if (tt < 200){
						tt = 200;
					}
					document.getElementById("text-input").rows = tt;

				};
				input.editor = this;
				var images = document.getElementsByTagName('img');
				this.update();
			}
			var $ = function (id) { return document.getElementById(id); };
			new Editor($("text-input"), $("preview"));

		</script>
	</body>
</html>

wiki/web/templates/footer.html
<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML' async></script>
<script type="text/javascript" src="{{ url_for('static', filename='showdown.min.js')}}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='markdown.min.js')}}"></script>
<script type="text/javascript">
  if (typeof jQuery == 'undefined') {
    document.write(unescape("%3Cscript src='{{ url_for('static', filename='jquery.min.js') }}' type='text/javascript'%3E%3C/script%3E"));
  }
</script>
<script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>

wiki/web/templates/head.html
<head>
	<title>{{ config.TITLE }}</title>
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='pygments.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap.min.css') }}">
	<style>
		@media (min-width: 768px) {.my-sidebar {position: fixed;}}
	</style>
</head>

wiki/web/templates/helpers.html
{% macro input(field) -%}
	<div class="{% if field.errors %}error{% endif %} form-group">
		{% if field.type == 'BooleanField' %}
			<div class="controls">
				<div class="checkbox"><label for="{{ field.name }}" class="">
					{{ field(**kwargs) }}
					{{ field.label.text }}
				</label></div>
			</div>
		{% else %}
			<label for="{{ field.name }}" class="control-label">{{ field.label.text }}</label>
			<div class="controls">
				{{ field(**kwargs) }}
				{% if field.errors %}
					<div>
						{% for error in field.errors %}
							<span class="help-block">
								{{ error }}
							</span>
						{% endfor %}
					</div>
				{% endif %}
			</div>
		{% endif %}
	</div>
{%- endmacro %}

wiki/web/templates/home.html
{% extends "base.html" %}
{% block title -%}
	Welcome to your new wiki!
{% endblock title %}

{% block content %}
<p>You did not create any content yet. Your wiki recommends you, to do so now, as every user will see this page first, and you would want to make a good impression, wouldn't you?</p>
<p><a href="{{ url_for('wiki.edit', url='home') }}" class="btn btn-success">Create a homepage</a></p>
{% endblock %}

wiki/web/templates/index.html
{% extends "base.html" %}

{% block title %}Page Index{% endblock title %}

{% block content %}

{% if directories %}
	<table class="table">
		<thead>
			<tr>
				<th>SubDirectory Title</th>
			</tr>
		</thead>
		<tbody>
			{% for dir in directories %}
				<tr>
					<td><a href="{{ url_for('wiki.display', url=dir.url) }}">{{ dir.title }}</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<p>There are no directories yet.</p>
{% endif %}

{% if pages %}
	<table class="table">
		<thead>
			<tr>
				<th>Page Title</th>
				<th>URL</th>
			</tr>
		</thead>
		<tbody>
			{% for page in pages %}
				<tr>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.title }}</a></td>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.url }}</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<p>There are no pages yet.</p>
{% endif %}
{% endblock content %}

{% block sidebar %}
	<h3>Actions</h3>
  <button type="button" class="btn btn-dark" onclick="window.location.href='{{ url_for('wiki.create') }}'">New Page</button>
  <button type="button" class="btn btn-dark" onclick="window.location.href='{{ url_for('wiki.tags') }}'">Tag List</button>
{% endblock sidebar %}

wiki/web/templates/menu.html
	<div class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
		<div class="container">
		<a class="navbar-brand" href="{{ url_for('wiki.home') }}">{{ config.TITLE }}</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#myNavbar" aria-controls="myNavbar" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="myNavbar">
			<ul class="navbar-nav mr-auto">
				<ul class="nav navbar-nav">
					<li class="nav-item"><a class="nav-link" href="{{ url_for('wiki.home') }}">Home</a></li>
					<li class="nav-item"><a class="nav-link" href="{{ url_for('wiki.index') }}">Index</a></li>
					<li class="nav-item"><a class="nav-link" href="{{ url_for('wiki.tags') }}">Tags</a></li>
					<li class="divider-vertical"></li>
					<li class="nav-item"><a class="nav-link" href="{{ url_for('wiki.create') }}">New Page</a></li>
					<li class="divider-vertical"></li>
					<li></li>
				</ul>
<!--
						<ul class="nav pull-right navbar-nav">
							{% if current_user.is_anonymous %}
								<li><a href="{{ url_for('wiki.user_login') }}">Login</a></li>
							{% else %}
								<li><a href="{{ url_for('wiki.user_logout') }}">Logout</a></li>
							{% endif %}
-->
				</ul>
					<form class="form-inline my-2 my-lg-0" method="POST" action="{{ url_for('wiki.search') }}">
						<input class="form-control mr-sm-2" id="term" name="term" type="text" placeholder="Search" {% if search is defined %} value="{{ search }}" {% endif %} aria-label="Search">
						<button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
					</form>
			</div>
			</div>
		</div>

wiki/web/templates/move.html
{% extends "base.html" %}

{% block title %}Move a page{% endblock title %}
{% block content %}
<form method="POST" class="form-inline">
    {{ form.hidden_tag() }}
    {{ input(form.url, placeholder="New URL of the page", autocomplete="off") }}
    <input type="submit" class="btn btn-success form-control" value="Create">
</form>
{% endblock content %}

{% block sidebar %}
<p class="alert alert-success">Be careful, the old url will be invalid immediately!</p>
{% endblock sidebar %}

wiki/web/templates/page.html
{% extends "base.html" %}

{% block title %}{{ page.title }}{% endblock title %}

{% block content %}

<!-- Modal -->
<div class="modal fade" id="confirmDelete" tabindex="-1" role="dialog" aria-labelledby="confirmDelete" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" ><h3>Are you sure?</h3></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Are you sure you want to delete {{ page.title }}?  This cannot be undone.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
        <button class="btn btn-danger"  onclick="window.location.href='{{ url_for('wiki.delete', url=page.url) }}'">Yes, delete.</button>
      </div>
    </div>
  </div>
</div>
	{{ page }}
{% endblock content %}

{% block sidebar %}
{% if page.tags %}
<h3>Tags</h3>
  <ul>
      {% for tag in page.tags.split(',') %}
        <li><a href="{{ url_for('wiki.tag', name=tag.strip()) }}">{{ tag|trim }}</a></li>
      {% endfor %}
  </ul>
{% endif %}

	<h3>Actions</h3>
  <button type="button" class="btn btn-dark" onclick="window.location.href='{{ url_for('wiki.edit', url=page.url) }}'">Edit</button>
  <button type="button" class="btn btn-dark" onclick="window.location.href='{{ url_for('wiki.move', url=page.url) }}'">Move</button>
  <button class="btn btn-danger text-error"  data-toggle="modal" data-target="#confirmDelete" >Delete</button>

  <h3>Index</h3>
  <div id="toc-sidebar">
  </div>
{% endblock sidebar %}

wiki/web/templates/search.html
{% extends "base.html" %}

{% block title %}
{% if search %}
	Results for "{{ search }}"
{% else %}
	Search
{% endif %}
{% endblock title %}

{% block content %}
{% if search %}
	{% if results %}
		<ul>
			{% for result in results %}
				<li><a href="{{ url_for('wiki.display', url=result.url) }}">{{ result.title }}</a></li>
			{% endfor %}
		</ul>
	{% else %}
		<p>No results for your search.</p>
	{% endif %}
{% endif %}
{% endblock content %}

wiki/web/templates/tag.html
{% extends "base.html" %}

{% block title %}Pages tagged {{ tag }}{% endblock title %}

{% block content %}
{% if pages %}
	<table class="table">
		<thead>
			<tr>
				<th>Title</th>
				<th>URL</th>
			</tr>
		</thead>
		<tbody>
			{% for page in pages %}
				<tr>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.title }}</a></td>
					<td><a href="{{ url_for('wiki.display', url=page.url) }}">{{ page.url }}</a></td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<p>There are no pages tagged {{ tag }}.</p>
{% endif %}
{% endblock content %}

wiki/web/templates/tags.html
{% extends "base.html" %}

{% block title %}Index by Tags{% endblock title %}

{% block content %}
{% if tags %}
	<table class="table">
		<thead>
			<tr>
				<th>Tag</th>
				<th>Number of Articles</th>
			</tr>
		</thead>
		<tbody>
			{% for tag, pages in tags|dictsort %}
				<tr>
					<td><a href="{{ url_for('wiki.tag', name=tag) }}">{{ tag }}</a></td>
					<td>{{ pages|length }}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% else %}
	<p>There are no tags in use so far.</p>
{% endif %}
{% endblock content %}